# Generated by Django 5.0 on 2024-04-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_alter_billing_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
