# Generated by Django 5.0 on 2024-04-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_billing_final_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='payment_mode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
