# Generated by Django 5.0 on 2024-04-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_billing_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
    ]
