# Generated by Django 5.0 on 2024-04-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='after_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
