# Generated by Django 5.0 on 2024-04-05 09:20

import bills.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_alter_invoice_after_discount_alter_invoice_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=bills.models.CustomAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
