# Generated by Django 5.0 on 2024-04-22 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return_and_refund',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('action', models.CharField(choices=[('exchange', 'Exchange'), ('refund', 'Refund')], max_length=10)),
                ('reason', models.TextField()),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('transaction_complete_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.invoice')),
            ],
        ),
    ]
