# Generated by Django 5.0 on 2024-04-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_return_and_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_and_refund',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
