# Generated by Django 5.0 on 2024-04-23 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_return_and_refund_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defective',
            fields=[
                ('defective_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.invoiceitem')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.return_and_refund')),
            ],
        ),
    ]
