# Generated by Django 5.0 on 2024-04-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_defective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defective',
            name='product',
        ),
        migrations.AddField(
            model_name='defective',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
