# Generated by Django 5.0 on 2024-04-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='upload_image',
            field=models.ImageField(upload_to='Advertisement_images'),
        ),
    ]
