# Generated by Django 5.0 on 2024-03-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_staff_photo_alter_staff_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
