# Generated by Django 5.0 on 2024-03-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_staff_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.AutoField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
