# Generated by Django 5.0 on 2024-03-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
