# Generated by Django 5.0 on 2024-03-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_staff_role_alter_staff_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_details',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=200)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('account_no', models.CharField(max_length=16, unique=True)),
                ('pan_no', models.CharField(max_length=10, unique=True)),
                ('adhar_no', models.CharField(max_length=12, unique=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to='home.staff')),
            ],
        ),
        migrations.CreateModel(
            name='bank_details',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=200)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('account_no', models.CharField(max_length=16, unique=True)),
                ('pan_no', models.CharField(max_length=10, unique=True)),
                ('adhar_no', models.CharField(max_length=12, unique=True)),
                ('bank_staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.staff')),
            ],
        ),
    ]
