# Generated by Django 5.0 on 2024-03-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_account_details_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_details',
            name='account_no',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account_details',
            name='adhar_no',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account_details',
            name='bank_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account_details',
            name='branch_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account_details',
            name='ifsc_code',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='account_details',
            name='pan_no',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
