# Generated by Django 5.0 on 2024-03-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_account_details_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_img'),
        ),
    ]
