# Generated by Django 5.0 on 2024-03-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_leave_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_request',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
