# Generated by Django 5.0 on 2024-03-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_leave_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_request',
            name='review_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
