# Generated by Django 5.0 on 2024-05-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_leave_request_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
