# Generated by Django 5.0 on 2024-05-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_details',
            name='base_salary_per_hr',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
