# Generated by Django 5.0 on 2024-05-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_account_details_base_salary_per_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_details',
            name='base_salary_per_hr',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
