# Generated by Django 5.0 on 2024-05-06 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('home', '0017_account_details_base_salary_per_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('based_salary', models.IntegerField()),
                ('daily_working_hours', models.TimeField()),
                ('month_hours', models.TimeField()),
                ('penalty_hours', models.TimeField()),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_time', models.TimeField()),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.TimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.account_details')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.staff')),
            ],
        ),
    ]
