# Generated by Django 5.0 on 2024-05-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_remove_salary_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='daily_working_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='extra_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='month_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='penalty_hours',
            field=models.FloatField(),
        ),
    ]
